module.exports = function toReadable(number) {

    let object = {
        0: 'zero', 1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 
        6: 'six', 7: 'seven', 8: 'eight', 9: 'nine',
        10: 'ten', 11: 'eleven', 12: 'twelve', 13: 'thirteen', 
        14: 'fourteen', 15: 'fifteen', 16: 'sixteen', 17: 'seventeen',
        18: 'eighteen', 19: 'nineteen', 20: 'twenty', 21: 'thirty', 
        22: 'forty', 23: 'fifty', 24: 'sixty', 25: 'seventy', 26: 'eighty', 27: 'ninety', 28: 'hundred'
    };


    switch (number) {
        case 0: return object[0];
        case 1: return object[1];
        case 2: return object[2];
        case 3: return object[3];
        case 4: return object[4];
        case 5: return object[5];
        case 6: return object[6];
        case 7: return object[7];
        case 8: return object[8];
        case 9: return object[9];
        case 10: return object[10];
        case 11: return object[11];
        case 12: return object[12];
        case 13: return object[13];
        case 14: return object[14];
        case 15: return object[15];
        case 16: return object[16];
        case 17: return object[17];
        case 18: return object[18];
        case 19: return object[19];  
        case 20: return object[20];  
        case 21: return object[20] + ' ' +  object[1]; 
        case 22: return object[20] + ' ' +  object[2];
        case 23: return object[20] + ' ' +  object[3];
        case 24: return object[20] + ' ' +  object[4];
        case 25: return object[20] + ' ' +  object[5];
        case 26: return object[20] + ' ' +  object[6];
        case 27: return object[20] + ' ' +  object[7];
        case 28: return object[20] + ' ' +  object[8];
        case 29: return object[20] + ' ' +  object[9];
        case 30: return object[21];
        case 31: return object[21] + ' ' +  object[1]; 
        case 32: return object[21] + ' ' +  object[2];
        case 33: return object[21] + ' ' +  object[3];
        case 34: return object[21] + ' ' +  object[4];
        case 35: return object[21] + ' ' +  object[5];
        case 36: return object[21] + ' ' +  object[6];
        case 37: return object[21] + ' ' +  object[7];
        case 38: return object[21] + ' ' +  object[8];
        case 39: return object[21] + ' ' +  object[9];
        case 40: return object[22];
        case 41: return object[22] + ' ' +  object[1]; 
        case 42: return object[22] + ' ' +  object[2];
        case 43: return object[22] + ' ' +  object[3];
        case 44: return object[22] + ' ' +  object[4];
        case 45: return object[22] + ' ' +  object[5];
        case 46: return object[22] + ' ' +  object[6];
        case 47: return object[22] + ' ' +  object[7];
        case 48: return object[22] + ' ' +  object[8];
        case 49: return object[22] + ' ' +  object[9];
        case 50: return object[23];
        case 51: return object[23] + ' ' +  object[1]; 
        case 52: return object[23] + ' ' +  object[2];
        case 53: return object[23] + ' ' +  object[3];
        case 54: return object[23] + ' ' +  object[4];
        case 55: return object[23] + ' ' +  object[5];
        case 56: return object[23] + ' ' +  object[6];
        case 57: return object[23] + ' ' +  object[7];
        case 58: return object[23] + ' ' +  object[8];
        case 59: return object[23] + ' ' +  object[9];
        case 60: return object[24];
        case 61: return object[24] + ' ' +  object[1]; 
        case 62: return object[24] + ' ' +  object[2];
        case 63: return object[24] + ' ' +  object[3];
        case 64: return object[24] + ' ' +  object[4];
        case 65: return object[24] + ' ' +  object[5];
        case 66: return object[24] + ' ' +  object[6];
        case 67: return object[24] + ' ' +  object[7];
        case 68: return object[24] + ' ' +  object[8];
        case 69: return object[24] + ' ' +  object[9];
        case 70: return object[25];
        case 71: return object[25] + ' ' +  object[1]; 
        case 72: return object[25] + ' ' +  object[2];
        case 73: return object[25] + ' ' +  object[3];
        case 74: return object[25] + ' ' +  object[4];
        case 75: return object[25] + ' ' +  object[5];
        case 76: return object[25] + ' ' +  object[6];
        case 77: return object[25] + ' ' +  object[7];
        case 78: return object[25] + ' ' +  object[8];
        case 79: return object[25] + ' ' +  object[9];
        case 80: return object[26];
        case 81: return object[26] + ' ' +  object[1]; 
        case 82: return object[26] + ' ' +  object[2];
        case 83: return object[26] + ' ' +  object[3];
        case 84: return object[26] + ' ' +  object[4];
        case 85: return object[26] + ' ' +  object[5];
        case 86: return object[26] + ' ' +  object[6];
        case 87: return object[26] + ' ' +  object[7];
        case 88: return object[26] + ' ' +  object[8];
        case 89: return object[26] + ' ' +  object[9];
        case 90: return object[27];
        case 91: return object[27] + ' ' +  object[1]; 
        case 92: return object[27] + ' ' +  object[2];
        case 93: return object[27] + ' ' +  object[3];
        case 94: return object[27] + ' ' +  object[4];
        case 95: return object[27] + ' ' +  object[5];
        case 96: return object[27] + ' ' +  object[6];
        case 97: return object[27] + ' ' +  object[7];
        case 98: return object[27] + ' ' +  object[8];
        case 99: return object[27] + ' ' +  object[9];
        case 100: return object[1] + ' ' +  object[28];
        case 101: return object[1] + ' ' +  object[28] + ' ' + object[1]; 
        case 102: return object[1] + ' ' +  object[28] + ' ' + object[2];
        case 103: return object[1] + ' ' +  object[28] + ' ' + object[3];
        case 104: return object[1] + ' ' +  object[28] + ' ' + object[4];
        case 105: return object[1] + ' ' +  object[28] + ' ' + object[5];
        case 106: return object[1] + ' ' +  object[28] + ' ' + object[6];
        case 107: return object[1] + ' ' +  object[28] + ' ' + object[7];
        case 108: return object[1] + ' ' +  object[28] + ' ' + object[8];
        case 109: return object[1] + ' ' +  object[28] + ' ' + object[9];
        case 110: return object[1] + ' ' +  object[28] + ' ' + object[10];
        case 111: return object[1] + ' ' +  object[28] + ' ' + object[11];
        case 112: return object[1] + ' ' +  object[28] + ' ' + object[12];
        case 113: return object[1] + ' ' +  object[28] + ' ' + object[13];
        case 114: return object[1] + ' ' +  object[28] + ' ' + object[14];
        case 115: return object[1] + ' ' +  object[28] + ' ' + object[15];
        case 116: return object[1] + ' ' +  object[28] + ' ' + object[16];
        case 117: return object[1] + ' ' +  object[28] + ' ' + object[17];
        case 118: return object[1] + ' ' +  object[28] + ' ' + object[18];
        case 119: return object[1] + ' ' +  object[28] + ' ' + object[19];
        case 120: return object[1] + ' ' +  object[28] + ' ' + object[20];
        case 121: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 122: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 123: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 124: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 125: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 126: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 127: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 128: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 129: return object[1] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 130: return object[1] + ' ' +  object[28] + ' ' + object[21];
        case 131: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 132: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 133: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 134: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 135: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 136: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 137: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 138: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 139: return object[1] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 140: return object[1] + ' ' +  object[28] + ' ' + object[22];
        case 141: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 142: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 143: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 144: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 145: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 146: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 147: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 148: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 149: return object[1] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 150: return object[1] + ' ' +  object[28] + ' ' + object[23];
        case 151: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 152: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 153: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 154: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 155: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 156: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 157: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 158: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 159: return object[1] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 160: return object[1] + ' ' +  object[28] + ' ' + object[24];
        case 161: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 162: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 163: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 164: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 165: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 166: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 167: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 168: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 169: return object[1] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 170: return object[1] + ' ' +  object[28] + ' ' + object[25];
        case 171: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 172: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 173: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 174: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 175: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 176: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 177: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 178: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 179: return object[1] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 180: return object[1] + ' ' +  object[28] + ' ' + object[26];
        case 181: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 182: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 183: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 184: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 185: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 186: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 187: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 188: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 189: return object[1] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 190: return object[1] + ' ' +  object[28] + ' ' + object[27];
        case 191: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 192: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 193: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 194: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 195: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 196: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 197: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 198: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 199: return object[1] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 200: return object[2] + ' ' +  object[28];
        case 201: return object[2] + ' ' +  object[28] + ' ' + object[1]; 
        case 202: return object[2] + ' ' +  object[28] + ' ' + object[2];
        case 203: return object[2] + ' ' +  object[28] + ' ' + object[3];
        case 204: return object[2] + ' ' +  object[28] + ' ' + object[4];
        case 205: return object[2] + ' ' +  object[28] + ' ' + object[5];
        case 206: return object[2] + ' ' +  object[28] + ' ' + object[6];
        case 207: return object[2] + ' ' +  object[28] + ' ' + object[7];
        case 208: return object[2] + ' ' +  object[28] + ' ' + object[8];
        case 209: return object[2] + ' ' +  object[28] + ' ' + object[9];
        case 210: return object[2] + ' ' +  object[28] + ' ' + object[10];
        case 211: return object[2] + ' ' +  object[28] + ' ' + object[11];
        case 212: return object[2] + ' ' +  object[28] + ' ' + object[12];
        case 213: return object[2] + ' ' +  object[28] + ' ' + object[13];
        case 214: return object[2] + ' ' +  object[28] + ' ' + object[14];
        case 215: return object[2] + ' ' +  object[28] + ' ' + object[15];
        case 216: return object[2] + ' ' +  object[28] + ' ' + object[16];
        case 217: return object[2] + ' ' +  object[28] + ' ' + object[17];
        case 218: return object[2] + ' ' +  object[28] + ' ' + object[18];
        case 219: return object[2] + ' ' +  object[28] + ' ' + object[19];
        case 220: return object[2] + ' ' +  object[28] + ' ' + object[20];
        case 221: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 222: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 223: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 224: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 225: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 226: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 227: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 228: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 229: return object[2] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 230: return object[2] + ' ' +  object[28] + ' ' + object[21];
        case 231: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 232: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 233: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 234: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 235: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 236: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 237: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 238: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 239: return object[2] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 240: return object[2] + ' ' +  object[28] + ' ' + object[22];
        case 241: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 242: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 243: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 244: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 245: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 246: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 247: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 248: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 249: return object[2] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 250: return object[2] + ' ' +  object[28] + ' ' + object[23];
        case 251: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 252: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 253: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 254: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 255: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 256: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 257: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 258: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 259: return object[2] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 260: return object[2] + ' ' +  object[28] + ' ' + object[24];
        case 261: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 262: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 263: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 264: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 265: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 266: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 267: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 268: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 269: return object[2] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 270: return object[2] + ' ' +  object[28] + ' ' + object[25];
        case 271: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 272: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 273: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 274: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 275: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 276: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 277: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 278: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 279: return object[2] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 280: return object[2] + ' ' +  object[28] + ' ' + object[26];
        case 281: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 282: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 283: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 284: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 285: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 286: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 287: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 288: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 289: return object[2] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 290: return object[2] + ' ' +  object[28] + ' ' + object[27];
        case 291: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 292: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 293: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 294: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 295: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 296: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 297: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 298: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 299: return object[2] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 300: return object[3] + ' ' +  object[28];
        case 301: return object[3] + ' ' +  object[28] + ' ' + object[1]; 
        case 302: return object[3] + ' ' +  object[28] + ' ' + object[2];
        case 303: return object[3] + ' ' +  object[28] + ' ' + object[3];
        case 304: return object[3] + ' ' +  object[28] + ' ' + object[4];
        case 305: return object[3] + ' ' +  object[28] + ' ' + object[5];
        case 306: return object[3] + ' ' +  object[28] + ' ' + object[6];
        case 307: return object[3] + ' ' +  object[28] + ' ' + object[7];
        case 308: return object[3] + ' ' +  object[28] + ' ' + object[8];
        case 309: return object[3] + ' ' +  object[28] + ' ' + object[9];
        case 310: return object[3] + ' ' +  object[28] + ' ' + object[10];
        case 311: return object[3] + ' ' +  object[28] + ' ' + object[11];
        case 312: return object[3] + ' ' +  object[28] + ' ' + object[12];
        case 313: return object[3] + ' ' +  object[28] + ' ' + object[13];
        case 314: return object[3] + ' ' +  object[28] + ' ' + object[14];
        case 315: return object[3] + ' ' +  object[28] + ' ' + object[15];
        case 316: return object[3] + ' ' +  object[28] + ' ' + object[16];
        case 317: return object[3] + ' ' +  object[28] + ' ' + object[17];
        case 318: return object[3] + ' ' +  object[28] + ' ' + object[18];
        case 319: return object[3] + ' ' +  object[28] + ' ' + object[19];
        case 320: return object[3] + ' ' +  object[28] + ' ' + object[20];
        case 321: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 322: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 323: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 324: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 325: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 326: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 327: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 328: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 329: return object[3] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 330: return object[3] + ' ' +  object[28] + ' ' + object[21];
        case 331: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 332: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 333: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 334: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 335: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 336: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 337: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 338: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 339: return object[3] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 340: return object[3] + ' ' +  object[28] + ' ' + object[22];
        case 341: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 342: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 343: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 344: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 345: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 346: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 347: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 348: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 349: return object[3] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 350: return object[3] + ' ' +  object[28] + ' ' + object[23];
        case 351: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 352: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 353: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 354: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 355: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 356: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 357: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 358: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 359: return object[3] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 360: return object[3] + ' ' +  object[28] + ' ' + object[24];
        case 361: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 362: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 363: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 364: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 365: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 366: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 367: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 368: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 369: return object[3] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 370: return object[3] + ' ' +  object[28] + ' ' + object[25];
        case 371: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 372: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 373: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 374: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 375: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 376: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 377: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 378: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 379: return object[3] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 380: return object[3] + ' ' +  object[28] + ' ' + object[26];
        case 381: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 382: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 383: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 384: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 385: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 386: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 387: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 388: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 389: return object[3] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 390: return object[3] + ' ' +  object[28] + ' ' + object[27];
        case 391: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 392: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 393: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 394: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 395: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 396: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 397: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 398: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 399: return object[3] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 400: return object[4] + ' ' +  object[28];
        case 401: return object[4] + ' ' +  object[28] + ' ' + object[1]; 
        case 402: return object[4] + ' ' +  object[28] + ' ' + object[2];
        case 403: return object[4] + ' ' +  object[28] + ' ' + object[3];
        case 404: return object[4] + ' ' +  object[28] + ' ' + object[4];
        case 405: return object[4] + ' ' +  object[28] + ' ' + object[5];
        case 406: return object[4] + ' ' +  object[28] + ' ' + object[6];
        case 407: return object[4] + ' ' +  object[28] + ' ' + object[7];
        case 408: return object[4] + ' ' +  object[28] + ' ' + object[8];
        case 409: return object[4] + ' ' +  object[28] + ' ' + object[9];
        case 410: return object[4] + ' ' +  object[28] + ' ' + object[10];
        case 411: return object[4] + ' ' +  object[28] + ' ' + object[11];
        case 412: return object[4] + ' ' +  object[28] + ' ' + object[12];
        case 413: return object[4] + ' ' +  object[28] + ' ' + object[13];
        case 414: return object[4] + ' ' +  object[28] + ' ' + object[14];
        case 415: return object[4] + ' ' +  object[28] + ' ' + object[15];
        case 416: return object[4] + ' ' +  object[28] + ' ' + object[16];
        case 417: return object[4] + ' ' +  object[28] + ' ' + object[17];
        case 418: return object[4] + ' ' +  object[28] + ' ' + object[18];
        case 419: return object[4] + ' ' +  object[28] + ' ' + object[19];
        case 420: return object[4] + ' ' +  object[28] + ' ' + object[20];
        case 421: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 422: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 423: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 424: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 425: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 426: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 427: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 428: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 429: return object[4] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 430: return object[4] + ' ' +  object[28] + ' ' + object[21];
        case 431: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 432: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 433: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 434: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 435: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 436: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 437: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 438: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 439: return object[4] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 440: return object[4] + ' ' +  object[28] + ' ' + object[22];
        case 441: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 442: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 443: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 444: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 445: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 446: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 447: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 448: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 449: return object[4] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 450: return object[4] + ' ' +  object[28] + ' ' + object[23];
        case 451: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 452: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 453: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 454: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 455: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 456: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 457: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 458: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 459: return object[4] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 460: return object[4] + ' ' +  object[28] + ' ' + object[24];
        case 461: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 462: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 463: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 464: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 465: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 466: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 467: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 468: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 469: return object[4] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 470: return object[4] + ' ' +  object[28] + ' ' + object[25];
        case 471: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 472: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 473: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 474: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 475: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 476: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 477: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 478: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 479: return object[4] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 480: return object[4] + ' ' +  object[28] + ' ' + object[26];
        case 481: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 482: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 483: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 484: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 485: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 486: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 487: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 488: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 489: return object[4] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 490: return object[4] + ' ' +  object[28] + ' ' + object[27];
        case 491: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 492: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 493: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 494: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 495: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 496: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 497: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 498: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 499: return object[4] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 500: return object[5] + ' ' +  object[28];
        case 501: return object[5] + ' ' +  object[28] + ' ' + object[1]; 
        case 502: return object[5] + ' ' +  object[28] + ' ' + object[2];
        case 503: return object[5] + ' ' +  object[28] + ' ' + object[3];
        case 504: return object[5] + ' ' +  object[28] + ' ' + object[4];
        case 505: return object[5] + ' ' +  object[28] + ' ' + object[5];
        case 506: return object[5] + ' ' +  object[28] + ' ' + object[6];
        case 507: return object[5] + ' ' +  object[28] + ' ' + object[7];
        case 508: return object[5] + ' ' +  object[28] + ' ' + object[8];
        case 509: return object[5] + ' ' +  object[28] + ' ' + object[9];
        case 510: return object[5] + ' ' +  object[28] + ' ' + object[10];
        case 511: return object[5] + ' ' +  object[28] + ' ' + object[11];
        case 512: return object[5] + ' ' +  object[28] + ' ' + object[12];
        case 513: return object[5] + ' ' +  object[28] + ' ' + object[13];
        case 514: return object[5] + ' ' +  object[28] + ' ' + object[14];
        case 515: return object[5] + ' ' +  object[28] + ' ' + object[15];
        case 516: return object[5] + ' ' +  object[28] + ' ' + object[16];
        case 517: return object[5] + ' ' +  object[28] + ' ' + object[17];
        case 518: return object[5] + ' ' +  object[28] + ' ' + object[18];
        case 519: return object[5] + ' ' +  object[28] + ' ' + object[19];
        case 520: return object[5] + ' ' +  object[28] + ' ' + object[20];
        case 521: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 522: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 523: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 524: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 525: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 526: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 527: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 528: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 529: return object[5] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 530: return object[5] + ' ' +  object[28] + ' ' + object[21];
        case 531: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 532: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 533: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 534: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 535: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 536: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 537: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 538: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 539: return object[5] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 540: return object[5] + ' ' +  object[28] + ' ' + object[22];
        case 541: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 542: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 543: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 544: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 545: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 546: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 547: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 548: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 549: return object[5] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 550: return object[5] + ' ' +  object[28] + ' ' + object[23];
        case 551: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 552: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 553: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 554: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 555: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 556: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 557: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 558: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 559: return object[5] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 560: return object[5] + ' ' +  object[28] + ' ' + object[24];
        case 561: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 562: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 563: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 564: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 565: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 566: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 567: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 568: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 569: return object[5] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 570: return object[5] + ' ' +  object[28] + ' ' + object[25];
        case 571: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 572: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 573: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 574: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 575: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 576: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 577: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 578: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 579: return object[5] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 580: return object[5] + ' ' +  object[28] + ' ' + object[26];
        case 581: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 582: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 583: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 584: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 585: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 586: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 587: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 588: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 589: return object[5] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 590: return object[5] + ' ' +  object[28] + ' ' + object[27];
        case 591: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 592: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 593: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 594: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 595: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 596: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 597: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 598: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 599: return object[5] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 600: return object[6] + ' ' +  object[28];
        case 601: return object[6] + ' ' +  object[28] + ' ' + object[1]; 
        case 602: return object[6] + ' ' +  object[28] + ' ' + object[2];
        case 603: return object[6] + ' ' +  object[28] + ' ' + object[3];
        case 604: return object[6] + ' ' +  object[28] + ' ' + object[4];
        case 605: return object[6] + ' ' +  object[28] + ' ' + object[5];
        case 606: return object[6] + ' ' +  object[28] + ' ' + object[6];
        case 607: return object[6] + ' ' +  object[28] + ' ' + object[7];
        case 608: return object[6] + ' ' +  object[28] + ' ' + object[8];
        case 609: return object[6] + ' ' +  object[28] + ' ' + object[9];
        case 610: return object[6] + ' ' +  object[28] + ' ' + object[10];
        case 611: return object[6] + ' ' +  object[28] + ' ' + object[11];
        case 612: return object[6] + ' ' +  object[28] + ' ' + object[12];
        case 613: return object[6] + ' ' +  object[28] + ' ' + object[13];
        case 614: return object[6] + ' ' +  object[28] + ' ' + object[14];
        case 615: return object[6] + ' ' +  object[28] + ' ' + object[15];
        case 616: return object[6] + ' ' +  object[28] + ' ' + object[16];
        case 617: return object[6] + ' ' +  object[28] + ' ' + object[17];
        case 618: return object[6] + ' ' +  object[28] + ' ' + object[18];
        case 619: return object[6] + ' ' +  object[28] + ' ' + object[19];
        case 620: return object[6] + ' ' +  object[28] + ' ' + object[20];
        case 621: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 622: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 623: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 624: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 625: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 626: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 627: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 628: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 629: return object[6] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 630: return object[6] + ' ' +  object[28] + ' ' + object[21];
        case 631: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 632: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 633: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 634: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 635: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 636: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 637: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 638: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 639: return object[6] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 640: return object[6] + ' ' +  object[28] + ' ' + object[22];
        case 641: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 642: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 643: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 644: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 645: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 646: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 647: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 648: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 649: return object[6] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 650: return object[6] + ' ' +  object[28] + ' ' + object[23];
        case 651: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 652: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 653: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 654: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 655: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 656: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 657: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 658: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 659: return object[6] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 660: return object[6] + ' ' +  object[28] + ' ' + object[24];
        case 661: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 662: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 663: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 664: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 665: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 666: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 667: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 668: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 669: return object[6] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 670: return object[6] + ' ' +  object[28] + ' ' + object[25];
        case 671: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 672: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 673: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 674: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 675: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 676: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 677: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 678: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 679: return object[6] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 680: return object[6] + ' ' +  object[28] + ' ' + object[26];
        case 681: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 682: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 683: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 684: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 685: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 686: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 687: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 688: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 689: return object[6] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 690: return object[6] + ' ' +  object[28] + ' ' + object[27];
        case 691: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 692: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 693: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 694: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 695: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 696: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 697: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 698: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 699: return object[6] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 700: return object[7] + ' ' +  object[28];
        case 701: return object[7] + ' ' +  object[28] + ' ' + object[1]; 
        case 702: return object[7] + ' ' +  object[28] + ' ' + object[2];
        case 703: return object[7] + ' ' +  object[28] + ' ' + object[3];
        case 704: return object[7] + ' ' +  object[28] + ' ' + object[4];
        case 705: return object[7] + ' ' +  object[28] + ' ' + object[5];
        case 706: return object[7] + ' ' +  object[28] + ' ' + object[6];
        case 707: return object[7] + ' ' +  object[28] + ' ' + object[7];
        case 708: return object[7] + ' ' +  object[28] + ' ' + object[8];
        case 709: return object[7] + ' ' +  object[28] + ' ' + object[9];
        case 710: return object[7] + ' ' +  object[28] + ' ' + object[10];
        case 711: return object[7] + ' ' +  object[28] + ' ' + object[11];
        case 712: return object[7] + ' ' +  object[28] + ' ' + object[12];
        case 713: return object[7] + ' ' +  object[28] + ' ' + object[13];
        case 714: return object[7] + ' ' +  object[28] + ' ' + object[14];
        case 715: return object[7] + ' ' +  object[28] + ' ' + object[15];
        case 716: return object[7] + ' ' +  object[28] + ' ' + object[16];
        case 717: return object[7] + ' ' +  object[28] + ' ' + object[17];
        case 718: return object[7] + ' ' +  object[28] + ' ' + object[18];
        case 719: return object[7] + ' ' +  object[28] + ' ' + object[19];
        case 720: return object[7] + ' ' +  object[28] + ' ' + object[20];
        case 721: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 722: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 723: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 724: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 725: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 726: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 727: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 728: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 729: return object[7] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 730: return object[7] + ' ' +  object[28] + ' ' + object[21];
        case 731: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 732: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 733: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 734: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 735: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 736: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 737: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 738: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 739: return object[7] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 740: return object[7] + ' ' +  object[28] + ' ' + object[22];
        case 741: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 742: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 743: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 744: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 745: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 746: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 747: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 748: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 749: return object[7] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 750: return object[7] + ' ' +  object[28] + ' ' + object[23];
        case 751: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 752: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 753: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 754: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 755: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 756: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 757: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 758: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 759: return object[7] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 760: return object[7] + ' ' +  object[28] + ' ' + object[24];
        case 761: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 762: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 763: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 764: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 765: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 766: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 767: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 768: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 769: return object[7] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 770: return object[7] + ' ' +  object[28] + ' ' + object[25];
        case 771: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 772: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 773: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 774: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 775: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 776: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 777: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 778: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 779: return object[7] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 780: return object[7] + ' ' +  object[28] + ' ' + object[26];
        case 781: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 782: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 783: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 784: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 785: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 786: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 787: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 788: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 789: return object[7] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 790: return object[7] + ' ' +  object[28] + ' ' + object[27];
        case 791: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 792: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 793: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 794: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 795: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 796: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 797: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 798: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 799: return object[7] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 800: return object[8] + ' ' +  object[28];
        case 801: return object[8] + ' ' +  object[28] + ' ' + object[1]; 
        case 802: return object[8] + ' ' +  object[28] + ' ' + object[2];
        case 803: return object[8] + ' ' +  object[28] + ' ' + object[3];
        case 804: return object[8] + ' ' +  object[28] + ' ' + object[4];
        case 805: return object[8] + ' ' +  object[28] + ' ' + object[5];
        case 806: return object[8] + ' ' +  object[28] + ' ' + object[6];
        case 807: return object[8] + ' ' +  object[28] + ' ' + object[7];
        case 808: return object[8] + ' ' +  object[28] + ' ' + object[8];
        case 809: return object[8] + ' ' +  object[28] + ' ' + object[9];
        case 810: return object[8] + ' ' +  object[28] + ' ' + object[10];
        case 811: return object[8] + ' ' +  object[28] + ' ' + object[11];
        case 812: return object[8] + ' ' +  object[28] + ' ' + object[12];
        case 813: return object[8] + ' ' +  object[28] + ' ' + object[13];
        case 814: return object[8] + ' ' +  object[28] + ' ' + object[14];
        case 815: return object[8] + ' ' +  object[28] + ' ' + object[15];
        case 816: return object[8] + ' ' +  object[28] + ' ' + object[16];
        case 817: return object[8] + ' ' +  object[28] + ' ' + object[17];
        case 818: return object[8] + ' ' +  object[28] + ' ' + object[18];
        case 819: return object[8] + ' ' +  object[28] + ' ' + object[19];
        case 820: return object[8] + ' ' +  object[28] + ' ' + object[20];
        case 821: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 822: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 823: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 824: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 825: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 826: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 827: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 828: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 829: return object[8] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 830: return object[8] + ' ' +  object[28] + ' ' + object[21];
        case 831: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 832: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 833: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 834: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 835: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 836: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 837: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 838: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 839: return object[8] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 840: return object[8] + ' ' +  object[28] + ' ' + object[22];
        case 841: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 842: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 843: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 844: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 845: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 846: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 847: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 848: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 849: return object[8] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 850: return object[8] + ' ' +  object[28] + ' ' + object[23];
        case 851: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 852: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 853: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 854: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 855: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 856: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 857: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 858: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 859: return object[8] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 860: return object[8] + ' ' +  object[28] + ' ' + object[24];
        case 861: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 862: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 863: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 864: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 865: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 866: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 867: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 868: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 869: return object[8] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 870: return object[8] + ' ' +  object[28] + ' ' + object[25];
        case 871: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 872: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 873: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 874: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 875: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 876: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 877: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 878: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 879: return object[8] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 880: return object[8] + ' ' +  object[28] + ' ' + object[26];
        case 881: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 882: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 883: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 884: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 885: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 886: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 887: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 888: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 889: return object[8] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 890: return object[8] + ' ' +  object[28] + ' ' + object[27];
        case 891: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 892: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 893: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 894: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 895: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 896: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 897: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 898: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 899: return object[8] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
        case 900: return object[9] + ' ' +  object[28];
        case 901: return object[9] + ' ' +  object[28] + ' ' + object[1]; 
        case 902: return object[9] + ' ' +  object[28] + ' ' + object[2];
        case 903: return object[9] + ' ' +  object[28] + ' ' + object[3];
        case 904: return object[9] + ' ' +  object[28] + ' ' + object[4];
        case 905: return object[9] + ' ' +  object[28] + ' ' + object[5];
        case 906: return object[9] + ' ' +  object[28] + ' ' + object[6];
        case 907: return object[9] + ' ' +  object[28] + ' ' + object[7];
        case 908: return object[9] + ' ' +  object[28] + ' ' + object[8];
        case 909: return object[9] + ' ' +  object[28] + ' ' + object[9];
        case 910: return object[9] + ' ' +  object[28] + ' ' + object[10];
        case 911: return object[9] + ' ' +  object[28] + ' ' + object[11];
        case 912: return object[9] + ' ' +  object[28] + ' ' + object[12];
        case 913: return object[9] + ' ' +  object[28] + ' ' + object[13];
        case 914: return object[9] + ' ' +  object[28] + ' ' + object[14];
        case 915: return object[9] + ' ' +  object[28] + ' ' + object[15];
        case 916: return object[9] + ' ' +  object[28] + ' ' + object[16];
        case 917: return object[9] + ' ' +  object[28] + ' ' + object[17];
        case 918: return object[9] + ' ' +  object[28] + ' ' + object[18];
        case 919: return object[9] + ' ' +  object[28] + ' ' + object[19];
        case 920: return object[9] + ' ' +  object[28] + ' ' + object[20];
        case 921: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[1];
        case 922: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[2];
        case 923: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[3];
        case 924: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[4];
        case 925: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[5];
        case 926: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[6];
        case 927: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[7];
        case 928: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[8];
        case 929: return object[9] + ' ' +  object[28] + ' ' + object[20] + ' ' + object[9];
        case 930: return object[9] + ' ' +  object[28] + ' ' + object[21];
        case 931: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[1];
        case 932: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[2];
        case 933: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[3];
        case 934: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[4];
        case 935: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[5];
        case 936: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[6];
        case 937: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[7];
        case 938: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[8];
        case 939: return object[9] + ' ' +  object[28] + ' ' + object[21] + ' ' + object[9];
        case 940: return object[9] + ' ' +  object[28] + ' ' + object[22];
        case 941: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[1];
        case 942: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[2];
        case 943: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[3];
        case 944: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[4];
        case 945: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[5];
        case 946: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[6];
        case 947: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[7];
        case 948: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[8];
        case 949: return object[9] + ' ' +  object[28] + ' ' + object[22] + ' ' + object[9];
        case 950: return object[9] + ' ' +  object[28] + ' ' + object[23];
        case 951: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[1];
        case 952: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[2];
        case 953: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[3];
        case 954: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[4];
        case 955: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[5];
        case 956: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[6];
        case 957: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[7];
        case 958: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[8];
        case 959: return object[9] + ' ' +  object[28] + ' ' + object[23] + ' ' + object[9];
        case 960: return object[9] + ' ' +  object[28] + ' ' + object[24];
        case 961: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[1];
        case 962: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[2];
        case 963: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[3];
        case 964: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[4];
        case 965: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[5];
        case 966: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[6];
        case 967: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[7];
        case 968: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[8];
        case 969: return object[9] + ' ' +  object[28] + ' ' + object[24] + ' ' + object[9];
        case 970: return object[9] + ' ' +  object[28] + ' ' + object[25];
        case 971: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[1];
        case 972: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[2];
        case 973: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[3];
        case 974: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[4];
        case 975: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[5];
        case 976: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[6];
        case 977: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[7];
        case 978: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[8];
        case 979: return object[9] + ' ' +  object[28] + ' ' + object[25] + ' ' + object[9];
        case 980: return object[9] + ' ' +  object[28] + ' ' + object[26];
        case 981: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[1];
        case 982: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[2];
        case 983: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[3];
        case 984: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[4];
        case 985: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[5];
        case 986: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[6];
        case 987: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[7];
        case 988: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[8];
        case 989: return object[9] + ' ' +  object[28] + ' ' + object[26] + ' ' + object[9];
        case 990: return object[9] + ' ' +  object[28] + ' ' + object[27];
        case 991: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[1];
        case 992: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[2];
        case 993: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[3];
        case 994: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[4];
        case 995: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[5];
        case 996: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[6];
        case 997: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[7];
        case 998: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[8];
        case 999: return object[9] + ' ' +  object[28] + ' ' + object[27] + ' ' + object[9];
    }

}
